apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nginx
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: try-flux2-kustomization
  path: ./base
  prune: true
  healthChecks:
  - apiVersion: apps/v1
    kind: Deployment
    namespace: default
    name: nginx
